##spring:
##  redis:
##    host: 192.168.1.7
##    port: 6380
##    password: 111111
##    lettuce:
##      pool:
##        max-active: 8
##        max-wait: -1ms
##        max-idle: 8
##        min-idle: 8
#spring:
#  redis:
#    url: redis://root:111111@192.168.1.7:6380